### ISSUE TITLE
TypeError: JSBI.BigInt is not a function

### ISSUE THREAD

**Issue by Rapiz1** [dbusjs/mpris-service#42]
Node version:  12.0.0
Electron version:  5.0.6
Chrome version:  73.0.3683.121

I'm trying to add mpris support for a existing music player [rapiz1/petal](https://github.com/Rapiz1/Petal/tree/94e19158771fe947aa3f0308b3084d155cf2238e).
The project uses Webpack and react-scripts, which I have little knowledge of. Maybe it's caused by Webpack?

**Comment by Rapiz1** [comment]
Maybe the warning mentioned above is not the real problem.
I ran the program and got error like this:
```
App threw an error during load
TypeError: JSBI.BigInt is not a function
    at eval (webpack:///./node_modules/dbus-next/lib/marshallers.js?:255:24)
    at Object../node_modules/dbus-next/lib/marshallers.js (/home/rapiz/Source/Petal/public/main.js:503:1)
    at __webpack_require__ (/home/rapiz/Source/Petal/public/main.js:20:30)
    at eval (webpack:///./node_modules/dbus-next/lib/marshall.js?:5:21)
    at Object../node_modules/dbus-next/lib/marshall.js (/home/rapiz/Source/Petal/public/main.js:492:1)
    at __webpack_require__ (/home/rapiz/Source/Petal/public/main.js:20:30)
    at eval (webpack:///./node_modules/dbus-next/lib/message.js?:2:18)
    at Object../node_modules/dbus-next/lib/message.js (/home/rapiz/Source/Petal/public/main.js:514:1)
    at __webpack_require__ (/home/rapiz/Source/Petal/public/main.js:20:30)
    at eval (webpack:///./node_modules/dbus-next/lib/connection.js?:3:17)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: JSBI.BigInt is not a function
    at eval (webpack:///./node_modules/dbus-next/lib/marshallers.js?:255:24)
    at Object../node_modules/dbus-next/lib/marshallers.js (/home/rapiz/Source/Petal/public/main.js:503:1)
    at __webpack_require__ (/home/rapiz/Source/Petal/public/main.js:20:30)
    at eval (webpack:///./node_modules/dbus-next/lib/marshall.js?:5:21)
    at Object../node_modules/dbus-next/lib/marshall.js (/home/rapiz/Source/Petal/public/main.js:492:1)
    at __webpack_require__ (/home/rapiz/Source/Petal/public/main.js:20:30)
    at eval (webpack:///./node_modules/dbus-next/lib/message.js?:2:18)
    at Object../node_modules/dbus-next/lib/message.js (/home/rapiz/Source/Petal/public/main.js:514:1)
    at __webpack_require__ (/home/rapiz/Source/Petal/public/main.js:20:30)
    at eval (webpack:///./node_modules/dbus-next/lib/connection.js?:3:17)
```
Looks similar to   #23 . I will check up that.

**Comment by Rapiz1** [comment]
Tried to edit ./node_modules/mpris-sevice/src/index.js and ./node_modules/mpris-sevice/dist/index.js. Change `dbus.setBigIntCompat(true);` to `dbus.setBigIntCompat(false);` but did not work. The same error.
In my understanding of [node-dbus-next#Compat](https://github.com/dbusjs/node-dbus-next#node-compatibility), after I changed the compat option it would not use JSBI and it would not produce a error containing JSBI stuff. It's really confusing.

**Comment by acrisci** [comment]
> Change dbus.setBigIntCompat(true); to dbus.setBigIntCompat(false); but did not work.

This only affects what the public api returns. Internally, it still uses JSBI because it simplifies the code path. But maybe that should be revisited and we should make that dependency really optional since it seems to be causing webpack problems.

Can you link to your branch where you are working on the implementation so I can look at it?

**Comment by Rapiz1** [comment]
https://github.com/Rapiz1/Petal/tree/94e19158771fe947aa3f0308b3084d155cf2238e
I have not really implement it yet. Just tested.
`electron/mpris.js` mostly comes from `mpris-service` example code.
`electron/main.dev.js` just add the line `import './mpris'`

**Comment by acrisci** [comment]
Try this:

```diff
diff --git a/webpack/config.electron.js b/webpack/config.electron.js
index 297e8cb..208e647 100644
--- a/webpack/config.electron.js
+++ b/webpack/config.electron.js
@@ -15,5 +15,10 @@ module.exports = {
   target: 'electron-main',
   node: {
     __dirname: false
+  },
+  resolve: {
+    alias: {
+      jsbi: path.resolve(__dirname, '..', 'node_modules', 'jsbi', 'dist', 'jsbi-cjs.js')
+    }
   }
 }
```

Note that the exact solution above won't work because your `node_modules` is at a different relative path. You have to add the `'..'` to the resolve path.

**Comment by Rapiz1** [comment]
It works.Thanks :)
